# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('room_number', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('capacity', models.CharField(max_length=5)),
                ('vacancy', models.CharField(max_length=5)),
                ('additional_charges', models.BooleanField()),
            ],
        ),
    ]
