# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-11 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=6)),
                ('adhaar', models.CharField(max_length=12)),
                ('mobile_no', models.CharField(max_length=10)),
                ('parent_name', models.CharField(max_length=50)),
                ('parent_mobile', models.CharField(max_length=10)),
                ('address_l1', models.CharField(max_length=100)),
                ('address_l2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=6)),
                ('registration_date', models.DateTimeField(auto_now=True)),
                ('empid', models.CharField(default=manager.models.increment_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('employee_type', models.CharField(max_length=8)),
            ],
        ),
    ]
